<a href="https://colab.research.google.com/github/yashjain771/minor-project-ai/blob/main/Minor_project(Yash_Jain).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [15]:
x_train=x_train/255
x_test=x_test/255

In [16]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(522,activation='relu'))
model.add(tf.keras.layers.Dense(10,activation='softmax'))

In [17]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [18]:
model.fit(x_train,y_train,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1983 - accuracy: 0.9428
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0801 - accuracy: 0.9758
Epoch 3/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0508 - accuracy: 0.9836
Epoch 4/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0370 - accuracy: 0.9883
Epoch 5/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0266 - accuracy: 0.9915
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0215 - accuracy: 0.9932
Epoch 7/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0175 - accuracy: 0.9943
Epoch 8/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0145 - accuracy: 0.9952
Epoch 9/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0131 - accuracy: 0.9956
Epoch 10/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.010

In [19]:
y_pred = model.predict_classes(x_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [22]:
print(y_pred)
print(y_test)

[7 2 1 ... 4 5 6]
[7 2 1 ... 4 5 6]


In [23]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.9807

In [24]:
confusion_matrix(y_test,y_pred)

array([[ 973,    0,    0,    1,    0,    0,    3,    1,    2,    0],
       [   0, 1123,    1,    3,    0,    0,    2,    1,    5,    0],
       [   2,    0, 1011,    3,    1,    0,    2,    4,    8,    1],
       [   0,    0,    2, 1000,    0,    0,    0,    2,    6,    0],
       [   2,    0,    2,    0,  958,    0,    6,    2,    0,   12],
       [   3,    1,    0,   25,    1,  852,    3,    1,    3,    3],
       [   2,    2,    0,    1,    1,    1,  949,    0,    2,    0],
       [   2,    2,    7,    3,    0,    0,    0, 1005,    4,    5],
       [   0,    0,    2,    5,    5,    1,    4,    2,  952,    3],
       [   1,    2,    0,    7,    4,    2,    2,    4,    3,  984]])

In [27]:
model.save('digitrec.h5')